title: "Abkm Log Book"
remote_theme: "mmistakes/minimal-mistakes@4.27.1"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-YK3JX8FMS2" 

# Navigation bar items
nav:
  - title: "Posts"
    url: /posts/
  - title: "Archive"
    url: /year-archive/
  - title: "Search"
    url: /search/
  - title: "Tags"
    url: /tags/
  - title: "FAQ"
    url: /faq/

