baseURL = "https://abkm-ai.github.io/"
languageCode = "en-us"
title = "Abkm Log Book"
theme = "PaperMod"

[params.homeInfoParams]
  Title = "👋 Welcome to Abkm Log Book"
  Content = """
Hi, I’m Abdul. I’m using this space to document my notes based on learnings about AI and other topics that interest me.
I use tools like ChatGPT, Gemini, and other LLMs during my research, but the content here reflects my own synthesis, curiosity, and understanding.
I learn best by writing — and this notebook will always be a work in progress :)
"""

[[menu.main]]
  name = "Posts"
  url = "posts/"
  weight = 1

[[menu.main]]
  name = "Archive"
  url = "archives/"
  weight = 2


